Repository MicrosoftDocs/query-docs, pull requests merged in 2022-09, with the labels that each got.

#19 Repo sync for protected CLA branch
  query-languages/dax/dax-queries.md
  query-languages/dax/define-statement-dax.md
  query-languages/dax/evaluate-statement-dax.md
  query-languages/dax/measure-statement-dax.md
  query-languages/dax/orderby-statement-dax.md
  query-languages/dax/startat-statement-dax.md
  query-languages/dax/statements-dax.md
  query-languages/dax/toc.yml
  query-languages/dax/var-dax.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, CLA

#21 Repo sync for protected CLA branch
  query-languages/m/saphana-database.md
Labels: do-not-merge, Change sent to author, powerquery/svc, CLA

#15 Adjusting table's row-type's grammar to allow an empty field listto be empty
  query-languages/m/m-spec-consolidated-grammar.md
Labels: M language, Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge

#22 Repo sync for protected CLA branch
  query-languages/dax/information-functions-dax.md
  query-languages/dax/toc.yml
  query-languages/dax/userculture-function-dax.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, CLA

#23 Repo sync for protected CLA branch
  query-languages/m/saphana-database.md
Labels: do-not-merge, CLA

#24 Repo sync for protected CLA branch
  query-languages/m/docfx.json
Labels: do-not-merge, CLA, review-team-triage

#27 Repo sync for protected CLA branch
  query-languages/dax/dax-overview.md
  query-languages/m/power-query-m-function-reference.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, CLA

#30 Repo sync for protected CLA branch
  query-languages/m/csv-document.md
  query-languages/m/table-distinct.md
  query-languages/m/table-functions.md
  query-languages/m/table-hascolumns.md
  query-languages/m/table-insertrows.md
Labels: do-not-merge, Change sent to author, powerquery/svc, CLA

#31 Repo sync for protected CLA branch
  query-languages/m/date-dayofweek.md
  query-languages/m/time-second.md
Labels: do-not-merge, Change sent to author, powerquery/svc, CLA

#13 M Language Spec Type Corrections
  query-languages/m/m-spec-types.md
Labels: M language, Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge

#29 Clarifying #shared to reflect directly injected global identifiers
  query-languages/m/m-spec-sections.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge

#35 Repo sync for protected CLA branch
  query-languages/dax/userculture-function-dax.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, CLA

#36 Repo sync for protected CLA branch
  CONTRIBUTING.md
  README.md
Labels: do-not-merge, CLA, review-team-triage, needs-human-review
