Repository MicrosoftDocs/query-docs, pull requests merged in 2022-12, with the labels that each got.

#56 Repo sync for protected CLA branch
  query-languages/m/binary-fromtext.md
Labels: do-not-merge, Change sent to author, powerquery/svc, CLA

#57 Repo sync for protected CLA branch
  query-languages/dax/filter-functions-dax.md
  query-languages/dax/index-function-dax.md
  query-languages/dax/new-dax-functions.md
  query-languages/dax/offset-function-dax.md
  query-languages/dax/orderby-function-dax.md
  query-languages/dax/partitionby-function-dax.md
  query-languages/dax/toc.yml
  query-languages/dax/window-function-dax.md
Labels: do-not-merge, CLA

#58 Repo sync for protected CLA branch
  query-languages/dax/index-function-dax.md
  query-languages/dax/offset-function-dax.md
  query-languages/dax/window-function-dax.md
Labels: do-not-merge, CLA

#59 Repo sync for protected CLA branch
  query-languages/dax/index-function-dax.md
  query-languages/dax/offset-function-dax.md
Labels: do-not-merge, CLA

#49 Clarifying type equality comparisons
  query-languages/m/m-spec-types.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge
