Repository MicrosoftDocs/query-docs, pull requests merged in 2022-11, with the labels that each got.

#42 Ascribed type of a value clarification
  query-languages/m/m-spec-types.md
Labels: do-not-merge, Change sent to author, qualifies-for-auto-merge, powerquery/svc

#47 Repo sync for protected CLA branch
  query-languages/m/date-dayofyear.md
  query-languages/m/date-endofday.md
  query-languages/m/date-endofmonth.md
  query-languages/m/date-endofquarter.md
  query-languages/m/date-endofweek.md
  query-languages/m/date-endofyear.md
  query-languages/m/date-functions.md
  query-languages/m/date-startofday.md
  query-languages/m/date-startofmonth.md
  query-languages/m/date-startofquarter.md
  query-languages/m/date-startofweek.md
  query-languages/m/date-startofyear.md
  query-languages/m/date-weekofmonth.md
  query-languages/m/date-weekofyear.md
  query-languages/m/progress-datasourceprogress.md
  query-languages/m/saphana-database.md
  query-languages/m/table-replacevalue.md
  query-languages/m/time-endofhour.md
  query-languages/m/time-functions.md
  query-languages/m/time-startofhour.md
  query-languages/m/toc.yml
  query-languages/m/value-functions.md
Labels: do-not-merge, CLA

#50 Updated first item in the remarks
  query-languages/dax/generateseries-function.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, qualifies-for-auto-merge

#46 M Grammer Change: type supports primary-expression
  query-languages/m/m-spec-consolidated-grammar.md
  query-languages/m/m-spec-types.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge

#52 Repo sync for protected CLA branch
  query-languages/dax/evaluateandlog-function-dax.md
  query-languages/dax/new-dax-functions.md
  query-languages/dax/other-functions-dax.md
  query-languages/dax/toc.yml
  query-languages/dax/tocsv-function-dax.md
  query-languages/dax/tojson-function-dax.md
Labels: do-not-merge, CLA

#53 Repo sync for protected CLA branch
  query-languages/dax/new-dax-functions.md
Labels: do-not-merge, CLA
