Repository MicrosoftDocs/query-docs, pull requests merged in 2023-03, with the labels that each got.

#62 Revising to include try's new catch feature
  query-languages/m/m-spec-consolidated-grammar.md
  query-languages/m/m-spec-error-handling.md
Labels: do-not-merge, Change sent to author, powerquery/svc, needs-human-review

#70 Relational Operator -- expanding to reflect types text & binary, address cross-type comparisons (+ tweaks)
  query-languages/m/m-spec-operators.md
Labels: do-not-merge, Change sent to author, qualifies-for-auto-merge, powerquery/svc

#81 Make orderBy_expression required param of SAMPLE
  query-languages/dax/sample-function-dax.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, qualifies-for-auto-merge
