Repository MicrosoftDocs/query-docs, pull requests merged in 2023-04, with the labels that each got.

#86 Table.RemoveColumns Tweaks
  query-languages/m/table-removecolumns.md
Labels: do-not-merge, Change sent to author, qualifies-for-auto-merge, powerquery/svc

#96 Typo fix, adding null as compatible with null
  query-languages/m/m-spec-operators.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge

#98 Table typo fixes
  query-languages/m/m-spec-values.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge

#83 Added Date Table reference
  query-languages/dax/time-intelligence-functions-dax.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, qualifies-for-auto-merge
