Repository MicrosoftDocs/query-docs, pull requests merged in 2024-03, with the labels that each got.

#161 Optional parameters are implicitly nullable
  query-languages/m/m-spec-types.md
Labels: do-not-merge, Change sent to author, qualifies-for-auto-merge, powerquery/svc, aq-pr-triaged

#165 Adding missing line return
  query-languages/m/m-spec-consolidated-grammar.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge, aq-pr-triaged

#181 Update sumx-function-dax.md
  query-languages/dax/sumx-function-dax.md
Labels: do-not-merge, Change sent to author, powerbi/svc, dax/subsvc, qualifies-for-auto-merge, aq-pr-triaged

#171 Table.ExpandListColumn -- documenting behavior on nested table columns
  query-languages/m/table-expandlistcolumn.md
Labels: Change sent to author, powerquery/svc, ready-to-merge, needs-human-review, aq-pr-triaged

#168 Clarification Idea: DateTime.Date
  query-languages/m/datetime-date.md
Labels: Change sent to author, qualifies-for-auto-merge, powerquery/svc, ready-to-merge, aq-pr-triaged
